name: Build
on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - ".storybook/**"
      - "stories/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/build.yml"

jobs:
  next:
    name: Next.js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: |
          npm i -g corepack@latest
          corepack enable

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build Next.js
        run: pnpm next build

  storybook:
    name: Storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: |
          npm i -g corepack@latest
          corepack enable

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build Storybook
        run: pnpm storybook build
